#!/usr/bin/env bash
# Generate an Ansible inventory YAML by enumerating LXC containers (and the host itself)
# on a Proxmox VE node.
#
# Usage (run on the PVE host):
#   sudo bash tools/gen-ansible-inventory.sh > inventory.yml
#
# Or from your control machine:
#   ssh prod-pve 'bash -s' < tools/gen-ansible-inventory.sh > inventory.yml

set -u

if ! command -v pct >/dev/null; then
  echo "ERR: pct not found — run this on a Proxmox VE host" >&2
  exit 2
fi

HOST=$(hostname)
HOST_IP=$(hostname -I | awk '{print $1}')

cat <<HEADER
# Auto-generated by gen-ansible-inventory.sh on $HOST at $(date -Iseconds)
all:
  vars:
    ansible_user: root
  children:

    proxmox_hosts:
      hosts:
        $HOST:
          ansible_host: $HOST_IP
      vars:
        host_kind: proxmox-host
        kit_dest: /root/security

    lxc_containers:
      hosts:
HEADER

pct list 2>/dev/null | awk 'NR>1 {print $1, $2, $3}' | while read -r vmid status name; do
  [[ "$status" != "running" ]] && continue
  ip=$(pct exec "$vmid" -- bash -c "ip -br -4 a show eth0 2>/dev/null | awk '{print \$3}' | cut -d/ -f1" 2>/dev/null)
  [[ -z "$ip" ]] && continue
  hostn=$(pct config "$vmid" | awk '/^hostname:/ {print $2}')
  [[ -z "$hostn" ]] && hostn="ct-$vmid"
  echo "        $hostn:"
  echo "          ansible_host: $ip"
  echo "          pve_vmid: $vmid"
  echo "          pve_node: $HOST"
done

cat <<FOOTER
      vars:
        host_kind: lxc-container
        kit_dest: /root/security
FOOTER
